name: module_app
description: A new Flutter project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ######################### 组件 #########################
  module_index:
    path: ../index
  ######################### 组件 #########################

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
